import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Widget = Schema<'Widget'>;
export type WidgetUpsert = Schema<'WidgetUpsert'>;
export type ListWidgetsQuery = OperationQuery<'list_widgets'>;
