import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type AutoReplyRule = Schema<'AutoReplyRule'>;
export type AutoReplyRuleCreate = Schema<'AutoReplyRuleCreate'>;
export type ReorderRequest = Schema<'ReorderRequest'>;
export type ListAutoReplyRulesQuery = OperationQuery<'list_auto_reply_rules'>;
