#!/usr/bin/env node
/**
 * pnpm wt:new <track> [slug]   (SDD-01T §3.9)
 *
 * git worktree add ../../../lp-ui-<track> -b ui/<track>/<slug>, pnpm install (shared store),
 * apps/web/.env.local with unique ports: WEB_PORT = 3100 + n, MOCK_PORT = 4100 + n.
 * Run from apps/web of the main checkout.
 */
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const [track, slugArg] = process.argv.slice(2);
const tracks = JSON.parse(readFileSync(new URL('../../tracks.json', import.meta.url), 'utf8')).tracks;
if (!track || !tracks[track]) {
  console.error(`usage: pnpm wt:new <track> [slug]\ntracks: ${Object.keys(tracks).join(', ')}`);
  process.exit(1);
}
const slug = slugArg ?? tracks[track].name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const repoRoot = execSync('git rev-parse --show-toplevel', { encoding: 'utf8' }).trim();
const n = Object.keys(tracks).indexOf(track) + 1;
const dir = resolve(repoRoot, '..', `lp-ui-${track}`);
const branch = `ui/${track}/${slug}`;

if (existsSync(dir)) {
  console.error(`worktree ${dir} already exists — use pnpm wt:list / wt:prune`);
  process.exit(1);
}
execSync(`git worktree add "${dir}" -b ${branch}`, { stdio: 'inherit', cwd: repoRoot });
execSync('pnpm install --prefer-offline', { stdio: 'inherit', cwd: dir });

const webPort = 3100 + n;
const mockPort = 4100 + n;
const env = `# generated by pnpm wt:new for ${track}\nCORE_API_URL=http://localhost:${mockPort}\nMOCK_PORT=${mockPort}\nWEB_PORT=${webPort}\nPORT=${webPort}\nMOCK_LATENCY=1\nNEXT_PUBLIC_SENTRY_DISABLED="true"\n`;
writeFileSync(resolve(dir, 'apps/web/.env.local'), env);
console.log(`\n✔ worktree ${dir}\n  branch ${branch}\n  web http://localhost:${webPort} · mock http://localhost:${mockPort}\n  next: cd ${dir}/apps/web && pnpm wt:dev\n  read docs/tracks/${track}.md first`);
