import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Answer = Schema<'Answer'>;
export type AnswerCreate = Schema<'AnswerCreate'>;
export type Question = Schema<'Question'>;
export type ListQuestionsQuery = OperationQuery<'list_questions'>;
