import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Tag = Schema<'Tag'>;
export type TagCreate = Schema<'TagCreate'>;
export type ListTagsQuery = OperationQuery<'list_tags'>;
