import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Export = Schema<'Export'>;
export type Review = Schema<'Review'>;
export type ReviewActivity = Schema<'ReviewActivity'>;
export type ReviewComplaint = Schema<'ReviewComplaint'>;
export type ReviewComplaintCreate = Schema<'ReviewComplaintCreate'>;
export type ReviewCreateManual = Schema<'ReviewCreateManual'>;
export type ReviewNote = Schema<'ReviewNote'>;
export type ReviewNoteCreate = Schema<'ReviewNoteCreate'>;
export type ReviewReply = Schema<'ReviewReply'>;
export type ReviewReplyCreate = Schema<'ReviewReplyCreate'>;
export type ReviewReplyUpdate = Schema<'ReviewReplyUpdate'>;
export type ReviewSummary = Schema<'ReviewSummary'>;
export type ReviewUpdate = Schema<'ReviewUpdate'>;
export type ReviewVersion = Schema<'ReviewVersion'>;
export type ListReviewsQuery = OperationQuery<'list_reviews'>;
export type GetReviewsSummaryQuery = OperationQuery<'get_reviews_summary'>;
export type ExportReviewsQuery = OperationQuery<'export_reviews'>;
