import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Export = Schema<'Export'>;
export type ExportCreate = Schema<'ExportCreate'>;
export type KwicRow = Schema<'KwicRow'>;
export type RankingRow = Schema<'RankingRow'>;
export type RegionStat = Schema<'RegionStat'>;
export type ReviewAnalyticsSummary = Schema<'ReviewAnalyticsSummary'>;
export type StaffRow = Schema<'StaffRow'>;
export type TrendPoint = Schema<'TrendPoint'>;
export type GetReviewAnalyticsSummaryQuery = OperationQuery<'get_review_analytics_summary'>;
export type GetReviewTrendQuery = OperationQuery<'get_review_trend'>;
export type GetReviewRegionsQuery = OperationQuery<'get_review_regions'>;
export type GetReviewLocationsRankingQuery = OperationQuery<'get_review_locations_ranking'>;
export type GetReviewCitiesRankingQuery = OperationQuery<'get_review_cities_ranking'>;
export type GetReviewTagsRankingQuery = OperationQuery<'get_review_tags_ranking'>;
export type GetReviewPhrasesRankingQuery = OperationQuery<'get_review_phrases_ranking'>;
export type GetReviewTopicsRankingQuery = OperationQuery<'get_review_topics_ranking'>;
export type GetReviewStaffQuery = OperationQuery<'get_review_staff'>;
export type GetReviewConcordanceQuery = OperationQuery<'get_review_concordance'>;
export type ExportReviewAnalyticsQuery = OperationQuery<'export_review_analytics'>;
