import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Listing = Schema<'Listing'>;
export type ListingAction = Schema<'ListingAction'>;
export type ListingSummary = Schema<'ListingSummary'>;
export type SyncOperation = Schema<'SyncOperation'>;
export type ListListingsQuery = OperationQuery<'list_listings'>;
export type GetListingsSummaryQuery = OperationQuery<'get_listings_summary'>;
