import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type AiGenerateRequest = Schema<'AiGenerateRequest'>;
export type AiGenerateResponse = Schema<'AiGenerateResponse'>;
export type AiReplyProfile = Schema<'AiReplyProfile'>;
export type AiReplyProfileUpsert = Schema<'AiReplyProfileUpsert'>;
export type ListAiReplyProfilesQuery = OperationQuery<'list_ai_reply_profiles'>;
