import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Campaign = Schema<'Campaign'>;
export type CampaignFunnelPoint = Schema<'CampaignFunnelPoint'>;
export type CampaignUpsert = Schema<'CampaignUpsert'>;
export type Export = Schema<'Export'>;
export type QrExportRequest = Schema<'QrExportRequest'>;
export type SyncBatch = Schema<'SyncBatch'>;
export type ListReviewCampaignsQuery = OperationQuery<'list_review_campaigns'>;
export type GetCampaignFunnelQuery = OperationQuery<'get_campaign_funnel'>;
