import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Competitor = Schema<'Competitor'>;
export type RankHeatmap = Schema<'RankHeatmap'>;
export type RankProject = Schema<'RankProject'>;
export type RankProjectUpsert = Schema<'RankProjectUpsert'>;
export type RankTrendPoint = Schema<'RankTrendPoint'>;
export type ListRankProjectsQuery = OperationQuery<'list_rank_projects'>;
export type GetRankHeatmapQuery = OperationQuery<'get_rank_heatmap'>;
export type GetRankTrendQuery = OperationQuery<'get_rank_trend'>;
export type GetRankCompetitorsQuery = OperationQuery<'get_rank_competitors'>;
