import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Publication = Schema<'Publication'>;
export type PublicationCreate = Schema<'PublicationCreate'>;
export type ListPublicationsQuery = OperationQuery<'list_publications'>;
