import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type ListingMedia = Schema<'ListingMedia'>;
export type ListingMediaAction = Schema<'ListingMediaAction'>;
export type MediaAsset = Schema<'MediaAsset'>;
export type ListMediaAssetsQuery = OperationQuery<'list_media_assets'>;
export type ListListingMediaQuery = OperationQuery<'list_listing_media'>;
