import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type DuplicateAction = Schema<'DuplicateAction'>;
export type DuplicateCase = Schema<'DuplicateCase'>;
export type DuplicateSummary = Schema<'DuplicateSummary'>;
export type ListDuplicatesQuery = OperationQuery<'list_duplicates'>;
export type GetDuplicatesSummaryQuery = OperationQuery<'get_duplicates_summary'>;
