import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Conversation = Schema<'Conversation'>;
export type ConversationMessage = Schema<'ConversationMessage'>;
export type ConversationMessageCreate = Schema<'ConversationMessageCreate'>;
export type ListConversationsQuery = OperationQuery<'list_conversations'>;
export type ListConversationMessagesQuery = OperationQuery<'list_conversation_messages'>;
