import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Notification = Schema<'Notification'>;
export type NotificationSettings = Schema<'NotificationSettings'>;
export type ListNotificationsQuery = OperationQuery<'list_notifications'>;
