import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Export = Schema<'Export'>;
export type ExportCreate = Schema<'ExportCreate'>;
export type KeywordRow = Schema<'KeywordRow'>;
export type PresencePoint = Schema<'PresencePoint'>;
export type PresenceSummary = Schema<'PresenceSummary'>;
export type PresenceSyncCell = Schema<'PresenceSyncCell'>;
export type GetPresenceSummaryQuery = OperationQuery<'get_presence_summary'>;
export type GetPresenceTrendQuery = OperationQuery<'get_presence_trend'>;
export type GetPresenceSyncMatrixQuery = OperationQuery<'get_presence_sync_matrix'>;
export type GetPresencePlatformQuery = OperationQuery<'get_presence_platform'>;
export type GetPresenceKeywordsQuery = OperationQuery<'get_presence_keywords'>;
export type ExportPresenceQuery = OperationQuery<'export_presence'>;
