'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useTranslations } from 'next-intl';
import { useState } from 'react';
import { toast } from 'sonner';
import { Icons } from '@/components/icons';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from '@/components/ui/card';
import { Field, FieldDescription, FieldLabel } from '@/components/ui/field';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '@/components/ui/select';
import { LocationPicker } from '@/features/locations';
import { waitForExport } from '@/features/review-analytics';
import { useCan } from '@/features/session';
import { isApiError } from '@/lib/api';
import { cn } from '@/lib/utils';
import { exportQrPdfMutation } from '../api/mutations';
import { reviewCampaignsQueryOptions } from '../api/queries';
import { getExport } from '../api/service';
import type { QrExportRequest } from '../api/types';

const LAYOUTS: NonNullable<QrExportRequest['layout']>[] = ['a4_poster', 'table_tent', 'sticker'];

/** Decorative QR-like pattern for the layout preview (the real code is generated by core-api). */
function FakeQr({ className }: { className?: string }) {
  const cells: boolean[] = [];
  let seed = 7;
  for (let i = 0; i < 21 * 21; i++) {
    seed = (seed * 9301 + 49297) % 233280;
    const row = Math.floor(i / 21);
    const col = i % 21;
    const finder = (row < 7 && col < 7) || (row < 7 && col > 13) || (row > 13 && col < 7);
    cells.push(
      finder
        ? !(row % 6 === 0 || col % 6 === 0 || (row > 1 && row < 5 && col > 1 && col < 5)) === false
        : seed / 233280 > 0.55
    );
  }
  return (
    <svg
      viewBox='0 0 21 21'
      className={cn('size-24', className)}
      role='img'
      aria-hidden
      shapeRendering='crispEdges'
    >
      {cells.map(
        (on, i) =>
          on && (
            <rect
              key={i}
              x={i % 21}
              y={Math.floor(i / 21)}
              width='1'
              height='1'
              fill='currentColor'
            />
          )
      )}
    </svg>
  );
}

/** S-GEN-01 «QR-коды»: PDF per location — campaign, layout, scope → async export with a download toast. */
export function QrExport() {
  const t = useTranslations('review-generation.qr');
  const tc = useTranslations('common');
  const canEdit = useCan('reviews.reply');
  const queryClient = useQueryClient();
  const { data: campaigns } = useQuery(
    reviewCampaignsQueryOptions({ page: 1, page_size: 100, 'filter[channel]': ['qr'] })
  );
  const exp = useMutation(exportQrPdfMutation(queryClient));
  const [campaignId, setCampaignId] = useState('');
  const [layout, setLayout] = useState<NonNullable<QrExportRequest['layout']>>('a4_poster');
  const [groupIds, setGroupIds] = useState<string[]>([]);
  const [locationIds, setLocationIds] = useState<string[]>([]);
  const campaign = campaigns?.items.find((c) => c.id === campaignId) ?? campaigns?.items[0];

  const download = async () => {
    const id = toast.loading(t('started'));
    try {
      const started = await exp.mutateAsync({
        body: {
          layout,
          ...(locationIds.length ? { location_ids: locationIds } : {}),
          scope: groupIds.length ? groupIds.join(',') : 'all'
        }
      });
      const done = await waitForExport(getExport, started.id);
      toast.success(t('ready'), {
        id,
        action: { label: tc('download'), onClick: () => window.open(done.download_url!, '_blank') }
      });
    } catch (e) {
      toast.error(isApiError(e) ? (e.detail ?? e.message) : (e as Error).message, { id });
    }
  };

  return (
    <div className='grid gap-4 lg:grid-cols-[1fr_20rem]' data-testid='qr-export'>
      <Card>
        <CardHeader>
          <CardTitle>{t('title')}</CardTitle>
          <CardDescription>{t('description')}</CardDescription>
        </CardHeader>
        <CardContent className='flex flex-col gap-4'>
          <Field>
            <FieldLabel htmlFor='qr-campaign'>{t('campaign')}</FieldLabel>
            <Select value={campaign?.id ?? ''} onValueChange={(v) => setCampaignId(v ?? '')}>
              <SelectTrigger id='qr-campaign' aria-label={t('campaign')} className='max-w-sm'>
                <SelectValue placeholder={t('noCampaign')}>
                  {(v: string) => campaigns?.items.find((c) => c.id === v)?.name ?? ''}
                </SelectValue>
              </SelectTrigger>
              <SelectContent>
                {(campaigns?.items ?? []).map((c) => (
                  <SelectItem key={c.id} value={c.id}>
                    {c.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <FieldDescription>
              {campaign?.short_link
                ? t('link', { link: campaign.short_link })
                : t('noCampaignHint')}
            </FieldDescription>
          </Field>
          <Field>
            <FieldLabel>{t('layout')}</FieldLabel>
            <RadioGroup
              value={layout}
              onValueChange={(v) => setLayout((v as typeof layout) ?? 'a4_poster')}
              className='grid gap-2 sm:grid-cols-3'
            >
              {LAYOUTS.map((l) => (
                <Label
                  key={l}
                  className={cn(
                    'flex cursor-pointer items-start gap-3 rounded-lg border p-3 font-normal',
                    layout === l && 'border-primary bg-primary/5'
                  )}
                >
                  <RadioGroupItem value={l} className='mt-0.5' data-testid={`qr-layout-${l}`} />
                  <span className='flex flex-col'>
                    <span className='font-medium'>{t(`layouts.${l}.title`)}</span>
                    <span className='text-muted-foreground text-xs'>{t(`layouts.${l}.hint`)}</span>
                  </span>
                </Label>
              ))}
            </RadioGroup>
          </Field>
          <Field>
            <FieldLabel>{t('scope')}</FieldLabel>
            <div className='flex flex-wrap items-center gap-3 text-sm'>
              <span>
                {groupIds.length + locationIds.length === 0
                  ? t('scopeAll')
                  : t('scopeSelected', { count: groupIds.length + locationIds.length })}
              </span>
              <LocationPicker
                value={{ location_ids: locationIds, group_ids: groupIds }}
                onChange={(v) => {
                  setLocationIds(v.location_ids);
                  setGroupIds(v.group_ids);
                }}
                allowGroups
              />
            </div>
            <FieldDescription>{t('scopeHint')}</FieldDescription>
          </Field>
        </CardContent>
        <CardFooter className='justify-end'>
          <Button
            onClick={download}
            disabled={!canEdit || !campaign || exp.isPending}
            data-testid='qr-download'
          >
            {exp.isPending ? (
              <Icons.spinner className='size-4 animate-spin' />
            ) : (
              <Icons.download className='size-4' />
            )}
            {t('download')}
          </Button>
        </CardFooter>
      </Card>

      <Card data-testid='qr-preview'>
        <CardHeader>
          <CardTitle>{t('preview')}</CardTitle>
          <CardDescription>{t(`layouts.${layout}.title`)}</CardDescription>
        </CardHeader>
        <CardContent className='flex justify-center'>
          <div
            className={cn(
              'bg-card flex flex-col items-center gap-3 rounded-md border p-4 text-center shadow-sm',
              layout === 'a4_poster' && 'aspect-[210/297] w-48',
              layout === 'table_tent' && 'aspect-[3/4] w-40',
              layout === 'sticker' && 'aspect-square w-36 rounded-full'
            )}
          >
            <span className='text-[11px] font-semibold'>
              {campaign?.message_template ?? t('previewText')}
            </span>
            <FakeQr className={layout === 'sticker' ? 'size-16' : 'size-24'} />
            <span className='text-muted-foreground text-[9px]'>
              {campaign?.short_link ?? 'lp.link/…'}
            </span>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
