import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type ReorderRequest = Schema<'ReorderRequest'>;
export type ReplyTemplate = Schema<'ReplyTemplate'>;
export type ReplyTemplateBulk = Schema<'ReplyTemplateBulk'>;
export type ReplyTemplateCreate = Schema<'ReplyTemplateCreate'>;
export type ReplyTemplateUpdate = Schema<'ReplyTemplateUpdate'>;
export type TemplateGroup = Schema<'TemplateGroup'>;
export type TemplateGroupCreate = Schema<'TemplateGroupCreate'>;
export type TemplateRenderRequest = Schema<'TemplateRenderRequest'>;
export type TemplateRenderResponse = Schema<'TemplateRenderResponse'>;
export type ListReplyTemplatesQuery = OperationQuery<'list_reply_templates'>;
export type ListTemplateGroupsQuery = OperationQuery<'list_template_groups'>;
