#!/usr/bin/env node
/**
 * pnpm scaffold:api <feature> --tags <tag,…> [--paths </prefix,…>] [--force]
 *
 * Generates src/features/<feature>/api/{types,service,queries,mutations}.ts from the OpenAPI
 * operations of the given tags (optionally narrowed by path prefixes) — SDD-01T §3.4.
 * Existing files are kept unless --force. The output is a starting point owned by the track.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { camel, listOperations, loadSpec, pascal } from './openapi.mjs';

const args = process.argv.slice(2);
const feature = args.find((a) => !a.startsWith('--'));
const opt = (name) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : undefined;
};
const force = args.includes('--force');
if (!feature) {
  console.error('usage: scaffold:api <feature> --tags reviews[,tags] [--paths /reviews] [--force]');
  process.exit(1);
}
const tags = (opt('tags') ?? feature).split(',').filter(Boolean);
const paths = (opt('paths') ?? '').split(',').filter(Boolean);

const spec = loadSpec();
const ops = listOperations(spec).filter((op) => !op.isStream && op.tags.some((t) => tags.includes(t)) && (paths.length === 0 || paths.some((p) => op.path.startsWith(p))));
if (!ops.length) {
  console.error(`scaffold:api: no operations for tags ${tags.join(', ')}`);
  process.exit(1);
}

const dir = resolve('src/features', feature, 'api');
mkdirSync(dir, { recursive: true });

const schemas = new Set();
for (const op of ops) {
  if (op.responseSchema) schemas.add(op.responseSchema);
  if (op.bodySchema) schemas.add(op.bodySchema);
}

// ── types.ts ────────────────────────────────────────────────────────────────
const hasQueryTypes = ops.some((o) => o.queryParams.length);
let types = `import type { ${hasQueryTypes ? 'OperationQuery, ' : ''}Schema } from '@lp/contracts';\n\n// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.\n`;
for (const s of [...schemas].sort()) types += `export type ${s} = Schema<'${s}'>;\n`;
for (const op of ops.filter((o) => o.queryParams.length)) types += `export type ${pascal(op.id)}Query = OperationQuery<'${op.id}'>;\n`;

// ── service.ts ──────────────────────────────────────────────────────────────
const usesQuery = ops.some((o) => o.queryParams.length);
const usesBody = ops.some((o) => o.hasBody);
let service = `import { coreClient${usesQuery ? ', query' : ''} } from '@/lib/api';\n${usesBody ? "import type { OperationBody } from '@lp/contracts';\n" : ''}`;
const queryTypes = ops.filter((o) => o.queryParams.length).map((o) => `${pascal(o.id)}Query`);
if (queryTypes.length) service += `import type { ${queryTypes.join(', ')} } from './types';\n`;
service += '\n';
for (const op of ops) {
  const fn = camel(op.id);
  const argParts = [];
  for (const p of op.pathParams) argParts.push(`${camel(p)}: ${p === 'version' ? 'number' : 'string'}`);
  if (op.hasBody) argParts.push(`body: OperationBody<'${op.id}'>`);
  if (op.isMultipart) argParts.push('form: FormData');
  if (op.queryParams.length) argParts.push(`params${op.queryParams.every((q) => !q.required) ? '?' : ''}: ${pascal(op.id)}Query`);
  const reqParts = [];
  if (op.pathParams.length || op.queryParams.length) {
    const inner = [];
    if (op.pathParams.length) inner.push(`path: { ${op.pathParams.map((p) => (camel(p) === p ? p : `${p}: ${camel(p)}`)).join(', ')} }`);
    if (op.queryParams.length) inner.push(`query: query(params ?? {})`);
    reqParts.push(`params: { ${inner.join(', ')} }`);
  }
  if (op.hasBody) reqParts.push('body');
  if (op.isMultipart) reqParts.push("body: form as never, bodySerializer: ((b: unknown) => b as FormData) as never");
  const noContent = op.successCode === '204' || op.successCode === '202' && !op.responseSchema;
  service += `/** ${op.method} ${op.path} — ${op.summary} */\nexport async function ${fn}(${argParts.join(', ')}) {\n`;
  service += noContent ? `  await coreClient().${op.method}('${op.path}'${reqParts.length ? `, { ${reqParts.join(', ')} }` : ''});\n}\n\n` : `  const { data } = await coreClient().${op.method}('${op.path}'${reqParts.length ? `, { ${reqParts.join(', ')} }` : ''});\n  return data!;\n}\n\n`;
}

// ── queries.ts ──────────────────────────────────────────────────────────────
const gets = ops.filter((o) => o.method === 'GET');
let queries = `import { queryOptions } from '@tanstack/react-query';\nimport { ${gets.map((o) => camel(o.id)).join(', ')} } from './service';\n`;
const getQueryTypes = gets.filter((o) => o.queryParams.length).map((o) => `${pascal(o.id)}Query`);
if (getQueryTypes.length) queries += `import type { ${getQueryTypes.join(', ')} } from './types';\n`;
const keyName = `${camel(feature)}Keys`;
queries += `\n/** Query keys: prefixed with the feature id; scoped lists include \`scope\` (SDD-01 §5.1). */\nexport const ${keyName} = {\n  all: ['${feature}'] as const,\n`;
const optQ = (op) => (op.queryParams.every((q) => !q.required) ? '?' : '');
for (const op of gets) {
  const k = camel(op.id.replace(/^(get|list)_/, ''));
  const argParts = [...op.pathParams.map((p) => `${camel(p)}: ${p === 'version' ? 'number' : 'string'}`), ...(op.queryParams.length ? [`params${optQ(op)}: ${pascal(op.id)}Query`] : [])];
  const scoped = op.queryParams.some((q) => q.name === 'scope');
  const keyParts = [`'${k}'`, ...op.pathParams.map(camel), ...(scoped ? ["params?.scope ?? 'all'"] : []), ...(op.queryParams.length ? ['params ?? {}'] : [])];
  queries += `  ${k}: (${argParts.join(', ')}) => [...${keyName}.all, ${keyParts.join(', ')}] as const,\n`;
}
queries = queries.replace(/,\n$/, '\n') + '};\n\n';
for (const op of gets) {
  const k = camel(op.id.replace(/^(get|list)_/, ''));
  const argParts = [...op.pathParams.map((p) => `${camel(p)}: ${p === 'version' ? 'number' : 'string'}`), ...(op.queryParams.length ? [`params${optQ(op)}: ${pascal(op.id)}Query`] : [])];
  const callArgs = [...op.pathParams.map(camel), ...(op.queryParams.length ? ['params'] : [])];
  queries += `export const ${k}QueryOptions = (${argParts.join(', ')}) =>\n  queryOptions({ queryKey: ${keyName}.${k}(${callArgs.join(', ')}), queryFn: () => ${camel(op.id)}(${callArgs.join(', ')}) });\n\n`;
}

// ── mutations.ts ────────────────────────────────────────────────────────────
const muts = ops.filter((o) => o.method !== 'GET');
let mutations = `import { mutationOptions, type QueryClient } from '@tanstack/react-query';\nimport { ${keyName} } from './queries';\nimport { ${muts.map((o) => camel(o.id)).join(', ')} } from './service';\n\n`;
for (const op of muts) {
  const fn = camel(op.id);
  const vars = [];
  let idx = op.pathParams.length;
  for (const p of op.pathParams) vars.push(`${camel(p)}: ${p === 'version' ? 'number' : 'string'}`);
  if (op.hasBody) vars.push(`body: Parameters<typeof ${fn}>[${idx++}]`);
  if (op.isMultipart) vars.push(`form: FormData`) && idx++;
  if (op.queryParams.length) vars.push(`params${op.queryParams.every((q) => !q.required) ? '?' : ''}: Parameters<typeof ${fn}>[${idx++}]`);
  const call = [...op.pathParams.map(camel), ...(op.hasBody ? ['body'] : []), ...(op.isMultipart ? ['form'] : []), ...(op.queryParams.length ? ['params'] : [])];
  const varsType = vars.length ? `{ ${vars.join('; ')} }` : 'void';
  const destructure = vars.length ? `({ ${call.join(', ')} }: ${varsType})` : '()';
  mutations += `export const ${fn}Mutation = (qc: QueryClient) =>\n  mutationOptions({\n    mutationKey: [...${keyName}.all, '${op.id}'],\n    mutationFn: ${destructure} => ${fn}(${call.join(', ')}),\n    onSuccess: () => qc.invalidateQueries({ queryKey: ${keyName}.all })\n  });\n\n`;
}

const files = { 'types.ts': types, 'service.ts': service, 'queries.ts': queries, 'mutations.ts': muts.length ? mutations : null };
for (const [name, content] of Object.entries(files)) {
  if (!content) continue;
  const file = resolve(dir, name);
  if (existsSync(file) && !force) {
    console.log(`scaffold:api: keep ${file} (exists)`);
    continue;
  }
  writeFileSync(file, content);
  console.log(`scaffold:api: wrote src/features/${feature}/api/${name}`);
}
console.log(`scaffold:api: ${ops.length} operation(s) for ${feature}: ${ops.map((o) => o.id).join(', ')}`);
