import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Product = Schema<'Product'>;
export type ProductUpsert = Schema<'ProductUpsert'>;
export type SyncBatch = Schema<'SyncBatch'>;
export type ListProductsQuery = OperationQuery<'list_products'>;
export type SyncProductsQuery = OperationQuery<'sync_products'>;
