import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type ApiKey = Schema<'ApiKey'>;
export type ApiKeyCreate = Schema<'ApiKeyCreate'>;
export type ApiKeyCreated = Schema<'ApiKeyCreated'>;
export type Tenant = Schema<'Tenant'>;
export type TenantUpdate = Schema<'TenantUpdate'>;
export type Webhook = Schema<'Webhook'>;
export type WebhookDelivery = Schema<'WebhookDelivery'>;
export type WebhookUpsert = Schema<'WebhookUpsert'>;
export type ListIntegrationsWebhooksQuery = OperationQuery<'list_integrations_webhooks'>;
export type ListWebhookDeliveriesQuery = OperationQuery<'list_webhook_deliveries'>;
