import type { OperationQuery, Schema } from '@lp/contracts';

// Re-exports only (SDD-01 §5.1) — no hand-written DTOs. Generated by scaffold:api, extend freely.
export type Invitation = Schema<'Invitation'>;
export type InvitationCreate = Schema<'InvitationCreate'>;
export type Membership = Schema<'Membership'>;
export type MembershipUpdate = Schema<'MembershipUpdate'>;
export type ListUsersQuery = OperationQuery<'list_users'>;
export type ListInvitationsQuery = OperationQuery<'list_invitations'>;
